[Interface]
PrivateKey = oNESeEFeoI5+3wOYCB/T+yM4uK/+Gjtzx/So6g+yYVA=
Address = 10.67.1.194/32
DNS = 1.1.1.1,1.0.0.1

[Peer]
PublicKey = 1Ulbw0GbKVAKxrQJ7j89uNY9cGu+n4yfr/NxaOwkYjc=
PresharedKey = eM2NeQZNdMnZeluzydehjv+yXgkaWUyZtW1Ga+sGJnw=
Endpoint = ruwg.lapti.win:10700
AllowedIPs = 0.0.0.0/0