[Interface]
PrivateKey = SHnCvGtWUiEZGnPDYdbcC1Kr4Y/nNMIt+OwafZ0KMk0=
Address = 10.67.1.196/32
DNS = 1.1.1.1,1.0.0.1

[Peer]
PublicKey = 1Ulbw0GbKVAKxrQJ7j89uNY9cGu+n4yfr/NxaOwkYjc=
PresharedKey = uNjRDZVFTdmk+yoFaLQf43dbd4b3sbzJCUQqIg2ccWI=
Endpoint = ruwg.lapti.win:10700
AllowedIPs = 0.0.0.0/0